[global]
flavor = "mdx"
# Exclude files/directories
exclude = ["node_modules", ".git", ".astro", "dist"]

# Set line length limit
line_length = 80

# Unordered list style
[MD004]
style = "dash"

# List indentation
[MD007]
style = "text-aligned"

# Ordered list style
[MD029]
style = "one-one"

[MD013]
line-length = 80
code-blocks = false
tables = false
reflow = true
reflow-mode = "default"

[MD025]
front-matter-title = "title"

[MD033]
enabled = false

[MD041]
enabled = false