[global]
flavor = "mdx"
# Exclude files/directories
exclude = ["node_modules", ".git", ".astro", "dist"]

# Set line length limit
line_length = 80

[MD013]
line_length = 80
code_blocks = false

[MD025]
front-matter-title = "title"

[MD033]
enabled = false

[MD041]
enabled = false