[global]
flavor = "mdx"
# Exclude files/directories
exclude = [
    "node_modules",
    ".git",
    "astro/.astro",
    "**/dist",
    "**/timeline-generated.mdx",
    ",specstory"
]

# Set line length limit
line_length = 80

# Unordered list style
[MD004]
style = "dash"

# List indentation
[MD007]
style = "text-aligned"

# Ordered list style
[MD029]
style = "one-one"

[MD013]
line-length = 100
code-blocks = false
tables = false
reflow = true
reflow-mode = "default"

[MD025]
front-matter-title = "title"

[MD033]
enabled = true
fix = true
allowed = ["table", "th", "tr", "td", "thead", "tbody"]
fix-mode = "relaxed"
br-style = "backslash"

[MD041]
enabled = false
