import { mkdir, open, readFile, rename, rm } from "node:fs/promises";
import { dirname, join } from "node:path";
import { randomUUID } from "node:crypto";
import { tmpdir } from "node:os";
import { spawn } from "node:child_process";
import { z } from "zod";
import { buildCodexExecArgs } from "./codex.js";
import { buildNotesFrontmatter } from "./notes.js";
import { stableHash } from "./reconciliationEvidence.js";
import type { CanonicalReconciliation } from "./reconciliation.js";

const MAX_RECORDS = 2048;
const MAX_REFS = 128;
const MAX_TIMEOUT_MS = 10 * 60_000;
const MAX_OUTPUT_BYTES = 20_000_000;
const MAX_PROMPT_BYTES = 2_000_000;
const text = z.string().trim().min(1).max(4000);
const boundedText = z.string().trim().min(1).max(400);
const flag = z.enum(["ambiguous-speaker", "unclear-words", "possible-omission", "attribution-uncertain", "material-correction"]);
export const ReviewDispositionSchema = z.enum(["carried_as_uncertain", "not_material_to_notes", "resolved_for_summary", "requires_human_review"]);
const confidence = z.enum(["high", "medium", "low"]);
const hash = z.string().regex(/^[0-9a-f]{64}$/u);
const uniqueRefs = z.array(boundedText).min(1).max(MAX_REFS).superRefine((xs, ctx) => { if (new Set(xs).size !== xs.length) ctx.addIssue({ code: "custom", message: "duplicate provenance reference" }); });
const flags = z.array(flag).max(8).superRefine((xs, ctx) => { if (new Set(xs).size !== xs.length) ctx.addIssue({ code: "custom", message: "duplicate review flag" }); });
const ClaimSchema = z.object({ id: boundedText, text, reconciliationBlockIds: uniqueRefs, confidence, attribution: boundedText.optional(), originalReviewFlags: flags }).strict();
const HookSchema = z.object({ id: boundedText, text, reconciliationBlockIds: uniqueRefs, originalReviewFlags: flags }).strict();
const DispositionSchema = z.object({ targetId: boundedText, disposition: ReviewDispositionSchema, originalReviewFlags: flags }).strict();
const SourceReviewTargetSchema = z.object({ id: boundedText, kind: z.enum(["suspicion-flag", "review-note"]), text: boundedText, originalReviewFlags: flags }).strict();
export const ChunkSummarySchema = z.object({ schemaVersion: z.literal("summary.chunk.v1"), cacheIdentity: hash, chunkId: boundedText, sourceSuspicionFlags: z.array(boundedText).max(MAX_RECORDS), reviewNotes: z.array(boundedText).max(MAX_RECORDS), sourceReviewTargets: z.array(SourceReviewTargetSchema).max(MAX_RECORDS), claims: z.array(ClaimSchema).max(MAX_RECORDS), unresolvedHooks: z.array(HookSchema).max(MAX_RECORDS), reviewDispositions: z.array(DispositionSchema).max(MAX_RECORDS), nextRollingContext: text }).strict();
export type ChunkSummary = z.infer<typeof ChunkSummarySchema>;
const SceneClaimSchema = z.object({ id: boundedText, text, chunkClaimIds: uniqueRefs }).strict();
const SceneHookSchema = z.object({ id: boundedText, text, chunkHookIds: uniqueRefs }).strict();
export const SceneSummarySchema = z.object({ schemaVersion: z.literal("summary.scene.v1"), cacheIdentity: hash, sceneId: z.string().regex(/^scene_\d{3}$/u), chunkIds: uniqueRefs, claims: z.array(SceneClaimSchema).max(MAX_RECORDS), unresolvedHooks: z.array(SceneHookSchema).max(MAX_RECORDS), chunkClaimProvenance: z.record(boundedText, uniqueRefs).superRefine((r, ctx) => { if (Object.keys(r).length > MAX_RECORDS) ctx.addIssue({ code: "custom", message: "too many provenance records" }); }) }).strict();
export type SceneSummary = z.infer<typeof SceneSummarySchema>;
const SessionClaimSchema = z.object({ id: boundedText, text, sceneClaimIds: uniqueRefs }).strict();
const SectionSchema = z.object({ id: boundedText, heading: boundedText, text, sceneClaimIds: uniqueRefs }).strict();
const SessionHookSchema = z.object({ id: boundedText, text, sceneHookIds: uniqueRefs }).strict();
export const SessionSummarySchema = z.object({ schemaVersion: z.literal("summary.session.v1"), cacheIdentity: hash, promptVersion: boundedText, claims: z.array(SessionClaimSchema).max(MAX_RECORDS), sections: z.array(SectionSchema).max(MAX_RECORDS), openHooks: z.array(SessionHookSchema).max(MAX_RECORDS), confirmationsNeeded: z.array(boundedText).max(MAX_RECORDS), boundaries: z.array(boundedText).max(MAX_RECORDS), provenanceMap: z.record(boundedText, uniqueRefs).superRefine((r, ctx) => { if (Object.keys(r).length > MAX_RECORDS) ctx.addIssue({ code: "custom", message: "too many provenance records" }); }), campaign: boundedText, sessionDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/u) }).strict();
export type SessionSummary = z.infer<typeof SessionSummarySchema>;

function ids(values: readonly { id: string }[], label: string): Set<string> { const out = new Set<string>(); for (const x of values) { if (out.has(x.id)) throw new Error(`duplicate ${label} id: ${x.id}`); out.add(x.id); } return out; }
function canonicalBlocks(canonical: CanonicalReconciliation | { chunk: { id: string }; blocks: readonly { id: string; reviewFlags?: readonly string[] }[] }): readonly { id: string; reviewFlags?: readonly string[] }[] { if (!canonical || !Array.isArray(canonical.blocks)) throw new Error("missing canonical reconciliation blocks"); return canonical.blocks; }
function canonicalId(canonical: { chunk: { id: string } }): string { if (!/^session_\d{3}$/u.test(canonical.chunk.id)) throw new Error(`unsafe chunk id: ${canonical.chunk.id}`); return canonical.chunk.id; }
function unionFlags(refs: readonly string[], blocks: readonly { id: string; reviewFlags?: readonly string[] }[]): string[] { const by = new Map(blocks.map((b) => [b.id, b.reviewFlags ?? []])); const out: string[] = []; for (const id of refs) for (const f of by.get(id) ?? []) if (!out.includes(f)) out.push(f); return out; }
function sameSet(a: readonly string[], b: readonly string[]): boolean { return a.length === b.length && new Set(a).size === a.length && a.every((x) => b.includes(x)); }
function sameSequence(a: readonly string[], b: readonly string[]): boolean { return a.length === b.length && a.every((x, index) => x === b[index]); }
function reviewTargets(canonical: CanonicalReconciliation): Array<{ id: string; kind: "suspicion-flag" | "review-note"; text: string; originalReviewFlags: string[] }> { const flags = (canonical.suspicionFlags ?? []).map((x, i) => ({ id: `suspicion:${stableHash(x)}:${i}`, kind: "suspicion-flag" as const, text: x, originalReviewFlags: [] as string[] })); const notes = (canonical.reviewNotes ?? []).map((x, i) => ({ id: `review-note:${stableHash(x)}:${i}`, kind: "review-note" as const, text: x, originalReviewFlags: [] as string[] })); return [...flags, ...notes]; }

export function parseChunkSummary(value: unknown, canonical: CanonicalReconciliation | { chunk: { id: string }; blocks: readonly { id: string; reviewFlags?: readonly string[] }[] }): ChunkSummary {
  const parsed = ChunkSummarySchema.parse(value); const blocks = canonicalBlocks(canonical); const blockIds = new Set(blocks.map((b) => b.id));
  if (parsed.chunkId !== canonicalId(canonical)) throw new Error(`chunk ID mismatch: ${parsed.chunkId}`);
  const canonicalFlags = (canonical as { suspicionFlags?: readonly string[] }).suspicionFlags ?? []; const canonicalNotes = (canonical as { reviewNotes?: readonly string[] }).reviewNotes ?? [];
  if (!sameSequence(parsed.sourceSuspicionFlags, canonicalFlags) || !sameSequence(parsed.reviewNotes, canonicalNotes)) throw new Error("source review material mismatch");
  const expectedTargets = reviewTargets(canonical as CanonicalReconciliation); if (JSON.stringify(parsed.sourceReviewTargets) !== JSON.stringify(expectedTargets)) throw new Error("source review targets mismatch");
  const all = [...parsed.claims, ...parsed.unresolvedHooks]; ids(all, "claim/hook");
  for (const item of all) { for (const ref of item.reconciliationBlockIds) if (!blockIds.has(ref)) throw new Error(`unknown reconciliation block: ${ref}`); const expected = unionFlags(item.reconciliationBlockIds, blocks); if (!sameSet(item.originalReviewFlags, expected)) throw new Error(`original review flags mismatch for ${item.id}`); }
  const targets = new Map<string, { id: string; originalReviewFlags: readonly string[] }>(); for (const x of all) targets.set(x.id, x); for (const x of parsed.sourceReviewTargets) targets.set(x.id, x); const seen = new Set<string>();
  for (const d of parsed.reviewDispositions) { if (seen.has(d.targetId)) throw new Error(`duplicate review disposition target: ${d.targetId}`); seen.add(d.targetId); const target = targets.get(d.targetId); if (!target) throw new Error(`unknown review disposition target: ${d.targetId}`); if (!sameSet(d.originalReviewFlags, target.originalReviewFlags)) throw new Error(`disposition flags mismatch for ${d.targetId}`); }
  for (const target of targets.values()) if (!seen.has(target.id)) throw new Error(`missing durable disposition for ${target.id}`);
  return parsed;
}

export function parseSceneSummary(value: unknown, chunks: readonly ChunkSummary[]): SceneSummary {
  const parsed = SceneSummarySchema.parse(value); const chunkBy = new Map(chunks.map((c) => [c.chunkId, c]));
  if (new Set(parsed.chunkIds).size !== parsed.chunkIds.length || parsed.chunkIds.some((id) => !chunkBy.has(id))) throw new Error("scene references unknown or duplicate chunk");
  const claims = new Map<string, ChunkSummary["claims"][number]>(), hooks = new Map<string, ChunkSummary["unresolvedHooks"][number]>();
  for (const c of chunks) { for (const x of c.claims) { if (claims.has(x.id)) throw new Error(`duplicate global chunk claim: ${x.id}`); claims.set(x.id, x); } for (const x of c.unresolvedHooks) { if (hooks.has(x.id)) throw new Error(`duplicate global chunk hook: ${x.id}`); hooks.set(x.id, x); } }
  ids(parsed.claims, "scene claim"); ids(parsed.unresolvedHooks, "scene hook");
  const includedClaims = new Set(parsed.chunkIds.flatMap((id) => chunkBy.get(id)!.claims.map((x) => x.id))); const includedHooks = new Set(parsed.chunkIds.flatMap((id) => chunkBy.get(id)!.unresolvedHooks.map((x) => x.id)));
  const representedClaims = new Set<string>(); for (const claim of parsed.claims) { for (const id of claim.chunkClaimIds) { if (!claims.has(id) || !includedClaims.has(id)) throw new Error("scene claim cites excluded or unknown chunk claim"); representedClaims.add(id); } }
  if (!sameSet([...representedClaims], [...includedClaims])) throw new Error("scene does not represent every included chunk claim");
  const provenanceKeys = Object.keys(parsed.chunkClaimProvenance); if (!sameSet(provenanceKeys, [...includedClaims])) throw new Error("scene chunk provenance is incomplete"); for (const claimId of provenanceKeys) { const refs = parsed.chunkClaimProvenance[claimId]!; const source = claims.get(claimId)!; if (!sameSet(refs, source.reconciliationBlockIds)) throw new Error(`scene chunk provenance mismatch for ${claimId}`); }
  const representedHooks = new Set<string>(); for (const hook of parsed.unresolvedHooks) { if (hook.chunkHookIds.some((id) => !hooks.has(id) || !includedHooks.has(id))) throw new Error("scene hook cites excluded or unknown chunk hook"); for (const id of hook.chunkHookIds) representedHooks.add(id); }
  if (!sameSet([...representedHooks], [...includedHooks])) throw new Error("scene does not represent every included chunk hook");
  return parsed;
}

export function parseSessionSummary(value: unknown, scenes: readonly SceneSummary[]): SessionSummary {
  const parsed = SessionSummarySchema.parse(value); ids(parsed.claims, "session claim"); ids(parsed.sections, "section"); ids(parsed.openHooks, "session hook");
  const sceneClaims = new Map<string, SceneSummary["claims"][number]>(), sceneHooks = new Map<string, SceneSummary["unresolvedHooks"][number]>(), blockRefs = new Map<string, string[]>(); for (const scene of scenes) { for (const claim of scene.claims) { if (sceneClaims.has(claim.id)) throw new Error(`duplicate global scene claim: ${claim.id}`); sceneClaims.set(claim.id, claim); } for (const hook of scene.unresolvedHooks) { if (sceneHooks.has(hook.id)) throw new Error(`duplicate global scene hook: ${hook.id}`); sceneHooks.set(hook.id, hook); } for (const [claimId, refs] of Object.entries(scene.chunkClaimProvenance)) blockRefs.set(claimId, refs); }
  const represented = new Set<string>(); for (const x of [...parsed.claims, ...parsed.sections]) for (const ref of x.sceneClaimIds) { if (!sceneClaims.has(ref)) throw new Error(`unknown scene claim: ${ref}`); represented.add(ref); } if (!sameSet([...represented], [...sceneClaims.keys()])) throw new Error("session omits a scene claim");
  const representedHooks = new Set<string>(); for (const hook of parsed.openHooks) for (const ref of hook.sceneHookIds) { if (!sceneHooks.has(ref)) throw new Error(`unknown scene hook: ${ref}`); representedHooks.add(ref); } if (!sameSet([...representedHooks], [...sceneHooks.keys()])) throw new Error("session omits a scene hook");
  const claimIds = new Set(parsed.claims.map((x) => x.id)); const keys = Object.keys(parsed.provenanceMap); if (keys.length !== claimIds.size || keys.some((k) => !claimIds.has(k))) throw new Error("provenanceMap keys must equal session claims");
  for (const claim of parsed.claims) { const chain = new Set<string>(); for (const sceneId of claim.sceneClaimIds) { const sc = sceneClaims.get(sceneId)!; chain.add(sc.id); for (const chunkClaimId of sc.chunkClaimIds) { chain.add(chunkClaimId); for (const blockId of blockRefs.get(chunkClaimId) ?? []) chain.add(blockId); } } const refs = parsed.provenanceMap[claim.id]!; if (!sameSet(refs, [...chain])) throw new Error(`incomplete provenance for ${claim.id}`); }
  return parsed;
}

export interface PromptOptions { canonical: CanonicalReconciliation | { chunk: unknown; blocks: readonly unknown[] }; priorRollingContext?: string; campaignContext?: string; correctionRules?: readonly string[]; flaggedAlternatives?: readonly { blockId: string; alternatives: readonly string[] }[]; promptVersion?: string }
const FlaggedAlternativeSchema = z.object({ blockId: boundedText, alternatives: z.array(boundedText).max(MAX_REFS) }).strict();
function boundedOptions(options: PromptOptions): void { boundedText.parse(options.promptVersion ?? "unspecified"); if (options.priorRollingContext !== undefined) z.string().max(4000).parse(options.priorRollingContext); if (options.campaignContext !== undefined) text.parse(options.campaignContext); z.array(text).max(MAX_RECORDS).parse(options.correctionRules ?? []); z.array(FlaggedAlternativeSchema).max(MAX_RECORDS).parse(options.flaggedAlternatives ?? []); }
export function buildChunkSummaryPrompt(options: PromptOptions): string { boundedOptions(options); const blocks = canonicalBlocks(options.canonical as never); const blockIds = new Set(blocks.map((b) => b.id)); const alternatives = options.flaggedAlternatives ?? []; const sourceReviewTargets = reviewTargets(options.canonical as CanonicalReconciliation); for (const x of alternatives) { if (!blockIds.has(x.blockId)) throw new Error(`unknown flagged alternative block: ${x.blockId}`); } return ["Return JSON only matching summary.chunk.v1.", `promptVersion: ${options.promptVersion ?? "unspecified"}.`, "Cite every claim and hook to supplied reconciliation block IDs; emit one durable disposition for every claim, hook, and supplied source-review target. Canonical source review material is injected by the caller.", "<chunk>", JSON.stringify((options.canonical as { chunk: unknown }).chunk), JSON.stringify(blocks), "</chunk>", "<source-review-targets>", JSON.stringify(sourceReviewTargets), "</source-review-targets>", "<prior-rolling-context>", options.priorRollingContext?.trim() || "None yet.", "</prior-rolling-context>", "<campaign-context>", options.campaignContext?.trim() || "None.", "</campaign-context>", "<correction-rules>", (options.correctionRules ?? []).join("\n") || "None.", "</correction-rules>", "<flagged-alternatives>", alternatives.map((x) => `${x.blockId}: ${x.alternatives.join(" | ")}`).join("\n") || "None.", "</flagged-alternatives>"].join("\n"); }

export interface SummaryChunkInput { canonical: CanonicalReconciliation | { chunk: { id: string }; blocks: readonly { id: string; reviewFlags?: readonly string[] }[] }; priorRollingContext?: string; flaggedAlternatives?: readonly { blockId: string; alternatives: readonly string[] }[] }
const ProviderIdentitySchema = z.object({ provider: boundedText, model: boundedText.optional(), profile: boundedText.optional() }).strict();
export interface ProviderIdentity { provider: string; model?: string; profile?: string }
export interface SummarizationOptions { outputRoot: string; repositoryCwd?: string; chunks: readonly (CanonicalReconciliation | SummaryChunkInput)[]; provider?: string; providerIdentity?: ProviderIdentity; promptVersion: string; schemaVersion?: string; campaignContext?: string; correctionRules?: readonly string[]; infer?: (input: { prompt: string; canonical: CanonicalReconciliation; priorRollingContext: string; signal?: AbortSignal }) => Promise<unknown>; sceneInfer?: (input: { prompt: string; chunks: readonly ChunkSummary[]; signal?: AbortSignal }) => Promise<unknown>; sessionInfer?: (input: { prompt: string; scenes: readonly SceneSummary[]; signal?: AbortSignal }) => Promise<unknown>; campaign?: string; sessionDate?: string; timeoutMs?: number; maxOutputBytes?: number; resume?: boolean; force?: boolean; sceneGroupSize?: number; beforeRename?: () => void | Promise<void>; codexCommand?: BoundedCodexCommand | string }
function boundedJsonBytes(value: unknown, maxOutputBytes: number, label: string): number { let serialized: string; try { serialized = JSON.stringify(value); } catch { throw new Error(`${label} output could not be serialized`); } const bytes = Buffer.byteLength(serialized); if (bytes > maxOutputBytes) throw new Error(`${label} output exceeds bound`); return bytes; }
async function boundedCall<T>(fn: (signal: AbortSignal) => Promise<T>, timeoutMs: number, maxOutputBytes: number, label: string): Promise<T> { const controller = new AbortController(); let timer: ReturnType<typeof setTimeout> | undefined; const task = fn(controller.signal).then((v) => { boundedJsonBytes(v, maxOutputBytes, label); return v; }); try { return await Promise.race([task, new Promise<T>((_, reject) => { timer = setTimeout(() => { controller.abort(); reject(new Error(`${label} timed out`)); }, timeoutMs); })]); } finally { if (timer) clearTimeout(timer); controller.abort(); } }
async function atomicJson(path: string, value: unknown, hook?: () => void | Promise<void>): Promise<void> { await mkdir(dirname(path), { recursive: true }); const temp = join(dirname(path), `.${randomUUID()}.tmp`); try { const h = await open(temp, "wx", 0o600); try { await h.writeFile(`${JSON.stringify(value, null, 2)}\n`, "utf8"); await h.sync(); } finally { await h.close(); } await hook?.(); await rename(temp, path); const d = await open(dirname(path), "r"); try { await d.sync(); } finally { await d.close(); } } finally { await rm(temp, { force: true }); } }
export interface BoundedCodexCommandInput { prompt: string; cwd: string; scratch: string; timeoutMs: number; maxOutputBytes: number; signal?: AbortSignal; command?: string }
export type BoundedCodexCommand = (input: BoundedCodexCommandInput) => Promise<unknown>;

function groupExists(pid: number | undefined): boolean { if (pid === undefined) return false; try { process.kill(-pid, 0); return true; } catch { return false; } }
function killGroup(pid: number | undefined, signal: NodeJS.Signals): void { if (pid === undefined || !groupExists(pid)) return; try { process.kill(-pid, signal); } catch { /* process-group lookup races are expected during close */ } }

export async function runBoundedCodexCommand(input: BoundedCodexCommandInput): Promise<unknown> {
  const output = join(input.scratch, "response.json");
  if (!Number.isInteger(input.timeoutMs) || input.timeoutMs < 1 || input.timeoutMs > MAX_TIMEOUT_MS) throw new Error("invalid Codex timeout");
  if (!Number.isInteger(input.maxOutputBytes) || input.maxOutputBytes < 1 || input.maxOutputBytes > MAX_OUTPUT_BYTES) throw new Error("invalid Codex output bound");
  if (Buffer.byteLength(input.prompt) > MAX_PROMPT_BYTES) throw new Error("Codex prompt exceeds bound");
  if (input.cwd.length > 4096 || input.scratch.length > 4096) throw new Error("Codex path exceeds bound");
  const child = spawn(input.command ?? "codex", buildCodexExecArgs({ cwd: input.cwd, outputPath: output }), { cwd: input.cwd, detached: true, stdio: ["pipe", "pipe", "pipe"] });
  const pid = child.pid;
  const timers = new Set<ReturnType<typeof setTimeout>>();
  const later = (ms: number, fn: () => void): ReturnType<typeof setTimeout> => { const timer = setTimeout(() => { timers.delete(timer); fn(); }, ms); timers.add(timer); return timer; };
  const cancelTimers = () => { for (const timer of timers) clearTimeout(timer); timers.clear(); };
  let total = 0; let overflow = false; let settled = false; let closed = false; let exited = false; let ownedGroupAfterExit = false; let timedOut = false; let aborted = false; let childError: Error | undefined;
  let termination: Promise<void> | undefined;
  const terminate = async (): Promise<void> => { if (termination) return termination; termination = (async () => { killGroup(pid, "SIGTERM"); await new Promise<void>((resolve) => later(100, resolve)); if ((!exited || ownedGroupAfterExit) && groupExists(pid)) killGroup(pid, "SIGKILL"); })(); return termination; };
  const waitForExit = new Promise<number | null>((resolve) => {
    child.once("error", (error) => { childError = error instanceof Error ? error : new Error(String(error)); resolve(null); });
    child.once("exit", (code) => { exited = true; ownedGroupAfterExit = groupExists(pid); resolve(code); });
    const collect = (chunk: Buffer | string) => { total += Buffer.byteLength(chunk); if (total > input.maxOutputBytes && !overflow) { overflow = true; void terminate(); } };
    child.stdout?.on("data", collect); child.stderr?.on("data", collect);
    child.stdout?.on("error", (error) => { childError ??= error instanceof Error ? error : new Error(String(error)); void terminate(); }); child.stderr?.on("error", (error) => { childError ??= error instanceof Error ? error : new Error(String(error)); void terminate(); }); child.stdin?.on("error", () => undefined);
    child.once("close", () => { closed = true; });
  });
  let timeout: ReturnType<typeof setTimeout> | undefined; let abortHandler: (() => void) | undefined;
  try {
    if (input.signal?.aborted) throw new Error("Codex aborted");
    abortHandler = () => { aborted = true; void terminate(); };
    input.signal?.addEventListener("abort", abortHandler, { once: true });
    timeout = later(input.timeoutMs, () => { timedOut = true; void terminate(); });
    child.stdin?.end(input.prompt);
    const code = await Promise.race([waitForExit, new Promise<never>((_, reject) => later(input.timeoutMs + 250, () => { void terminate().finally(() => reject(new Error("Codex timed out"))); }))]);
    if (overflow) throw new Error("Codex output exceeds bound");
    if (timedOut) throw new Error("Codex timed out");
    if (aborted) throw new Error("Codex aborted");
    if (childError) throw childError;
    if (code !== 0) throw new Error(`Codex failed with exit code ${code}`);
    const data = await readFile(output); if (data.byteLength > input.maxOutputBytes) throw new Error("Codex response exceeds bound");
    return JSON.parse(data.toString("utf8"));
  } finally {
    settled = true; if (timeout) clearTimeout(timeout); if (abortHandler) input.signal?.removeEventListener("abort", abortHandler); if (groupExists(pid)) await terminate(); cancelTimers(); await rm(output, { force: true }); void settled; void closed;
  }
}
function inputOf(value: CanonicalReconciliation | SummaryChunkInput): SummaryChunkInput { if (typeof value !== "object" || value === null) throw new Error("chunk input must be an object"); if ("canonical" in value) return value as SummaryChunkInput; return { canonical: value as CanonicalReconciliation }; }

function validateRunOptions(options: SummarizationOptions): void { if (!Array.isArray(options.chunks) || !options.chunks.length || options.chunks.length > MAX_RECORDS) throw new Error("chunks must be nonempty and bounded"); for (const raw of options.chunks) { const canonical = inputOf(raw).canonical; canonicalId(canonical as { chunk: { id: string } }); if (!canonicalBlocks(canonical as never).length) throw new Error("chunks must contain nonempty canonical blocks"); } boundedText.parse(options.promptVersion); if (options.provider !== undefined) boundedText.parse(options.provider); if (options.schemaVersion !== undefined) boundedText.parse(options.schemaVersion); if (options.campaign !== undefined) boundedText.parse(options.campaign); if (options.sessionDate !== undefined) z.string().regex(/^\d{4}-\d{2}-\d{2}$/u).parse(options.sessionDate); if (options.campaignContext !== undefined) text.parse(options.campaignContext); z.array(text).max(MAX_RECORDS).parse(options.correctionRules ?? []); z.array(FlaggedAlternativeSchema).max(MAX_RECORDS).parse(options.chunks.flatMap((raw) => inputOf(raw).flaggedAlternatives ?? [])); if (options.providerIdentity) ProviderIdentitySchema.parse(options.providerIdentity); if (options.timeoutMs !== undefined && (!Number.isInteger(options.timeoutMs) || options.timeoutMs < 1 || options.timeoutMs > MAX_TIMEOUT_MS)) throw new Error("invalid timeoutMs"); if (options.maxOutputBytes !== undefined && (!Number.isInteger(options.maxOutputBytes) || options.maxOutputBytes < 1 || options.maxOutputBytes > MAX_OUTPUT_BYTES)) throw new Error("invalid maxOutputBytes"); if (options.sceneGroupSize !== undefined && (!Number.isInteger(options.sceneGroupSize) || options.sceneGroupSize < 1 || options.sceneGroupSize > MAX_RECORDS)) throw new Error("invalid sceneGroupSize"); }
export async function runReconciliationSummarization(options: SummarizationOptions): Promise<{ chunks: ChunkSummary[]; scenes: SceneSummary[]; session: SessionSummary }> { validateRunOptions(options); const timeoutMs = options.timeoutMs ?? 120_000, maxOutputBytes = options.maxOutputBytes ?? 2_000_000, groupSize = options.sceneGroupSize ?? 5; const root = join(options.outputRoot, "summarization"), chunkDir = join(root, "chunks"), sceneDir = join(root, "scenes"); await mkdir(chunkDir, { recursive: true }); await mkdir(sceneDir, { recursive: true }); const providerIdentity = options.providerIdentity ?? { provider: options.provider ?? "codex", model: "codex", profile: "default" }; const chunks: ChunkSummary[] = []; let prior = ""; const scratch = await import("node:fs/promises").then((fs) => fs.mkdtemp(join(tmpdir(), "bf-summary-"))); const infer = async (prompt: string, cwd: string, signal?: AbortSignal) => typeof options.codexCommand === "function" ? options.codexCommand({ prompt, cwd, scratch, timeoutMs, maxOutputBytes, signal }) : runBoundedCodexCommand({ prompt, cwd, scratch, timeoutMs, maxOutputBytes, signal, command: options.codexCommand });
  try { for (const raw of options.chunks) { const input = inputOf(raw); const canonical = input.canonical as CanonicalReconciliation; const id = canonicalId(canonical); const prompt = buildChunkSummaryPrompt({ canonical, priorRollingContext: prior, campaignContext: options.campaignContext, correctionRules: options.correctionRules, flaggedAlternatives: input.flaggedAlternatives, promptVersion: options.promptVersion }); const identity = { type: "chunk", inputHash: stableHash(canonical), priorRollingContext: stableHash(prior), campaignContext: stableHash(options.campaignContext ?? ""), correctionRules: stableHash(options.correctionRules ?? []), flaggedAlternatives: stableHash(input.flaggedAlternatives ?? []), campaign: options.campaign ?? "", sessionDate: options.sessionDate ?? "", promptVersion: options.promptVersion, prompt: stableHash(prompt), schema: options.schemaVersion ?? "summary.v1", providerIdentity: stableHash(providerIdentity) }; const cacheIdentity = stableHash(identity); const path = join(chunkDir, `${id}.json`); let parsed: ChunkSummary | undefined; if (!options.force && options.resume !== false) { try { const disk = JSON.parse(await readFile(path, "utf8")); if (disk.cacheIdentity === cacheIdentity) parsed = parseChunkSummary(disk, canonical); } catch { /* stale/corrupt is repaired */ } } if (!parsed) { const rawResult = options.infer ? await boundedCall((signal) => options.infer!({ prompt, canonical, priorRollingContext: prior, signal }), timeoutMs, maxOutputBytes, "chunk inference") : await infer(prompt, options.repositoryCwd ?? process.cwd()); parsed = parseChunkSummary({ ...(rawResult as object), cacheIdentity, sourceSuspicionFlags: canonical.suspicionFlags, reviewNotes: canonical.reviewNotes, sourceReviewTargets: reviewTargets(canonical) }, canonical); await atomicJson(path, parsed, options.beforeRename); } chunks.push(parsed); prior = parsed.nextRollingContext; }
    const scenes: SceneSummary[] = []; for (let i = 0; i < chunks.length; i += groupSize) { const group = chunks.slice(i, i + groupSize), sceneId = `scene_${String(i / groupSize).padStart(3, "0")}`; const prompt = ["Return JSON only matching summary.scene.v1.", "Use exactly this sceneId; represent every included chunk claim and hook; scene hooks require complete chunkHookIds.", sceneId, JSON.stringify(group)].join("\n"); const identity = { type: "scene", sceneId, group: stableHash(group), prompt: stableHash(prompt), providerIdentity: stableHash(providerIdentity), promptVersion: options.promptVersion, campaign: options.campaign ?? "", sessionDate: options.sessionDate ?? "" }; const cacheIdentity = stableHash(identity), path = join(sceneDir, `${sceneId}.json`); let scene: SceneSummary | undefined; if (!options.force && options.resume !== false) { try { const disk = JSON.parse(await readFile(path, "utf8")); if (disk.cacheIdentity === cacheIdentity) scene = parseSceneSummary(disk, group); } catch { /* repair */ } } if (!scene) { const raw = options.sceneInfer ? await boundedCall((signal) => options.sceneInfer!({ prompt, chunks: group, signal }), timeoutMs, maxOutputBytes, "scene inference") : await infer(prompt, options.repositoryCwd ?? process.cwd()); scene = SceneSummarySchema.parse({ ...(raw as object), cacheIdentity, chunkClaimProvenance: Object.fromEntries(group.flatMap((c) => c.claims.map((claim) => [claim.id, claim.reconciliationBlockIds]))) }); scene = parseSceneSummary(scene, group); await atomicJson(path, scene, options.beforeRename); } scenes.push(scene); }
    const sessionPrompt = ["Return JSON only matching summary.session.v1.", `promptVersion: ${options.promptVersion}.`, "Represent every scene claim and scene hook; provenanceMap must include each final→scene→chunk→reconciliation-block chain.", JSON.stringify(scenes)].join("\n"); const sessionIdentity = { type: "session", scenes: stableHash(scenes), prompt: stableHash(sessionPrompt), providerIdentity: stableHash(providerIdentity), promptVersion: options.promptVersion, campaign: options.campaign ?? "", sessionDate: options.sessionDate ?? "" }; const sessionCacheIdentity = stableHash(sessionIdentity), sessionPath = join(root, "session.json"); let session: SessionSummary | undefined; if (!options.force && options.resume !== false) { try { const disk = JSON.parse(await readFile(sessionPath, "utf8")); if (disk.cacheIdentity === sessionCacheIdentity) session = parseSessionSummary(disk, scenes); } catch { /* repair */ } } if (!session) { const raw = options.sessionInfer ? await boundedCall((signal) => options.sessionInfer!({ prompt: sessionPrompt, scenes, signal }), timeoutMs, maxOutputBytes, "session inference") : await infer(sessionPrompt, options.repositoryCwd ?? process.cwd()); session = SessionSummarySchema.parse({ ...(raw as object), cacheIdentity: sessionCacheIdentity, promptVersion: options.promptVersion }); session = parseSessionSummary(session, scenes); await atomicJson(sessionPath, session, options.beforeRename); } return { chunks, scenes, session }; } finally { await rm(scratch, { recursive: true, force: true }); } }

export function renderSessionMdx(value: unknown, authoritativeScenes: readonly SceneSummary[]): string { const session = parseSessionSummary(value, authoritativeScenes); const body = session.sections.map((s) => `## ${s.heading}\n\n${s.text}`).join("\n\n"); const optional = ([ ["Open Hooks", session.openHooks.map((x) => x.text)], ["Confirmations Needed", session.confirmationsNeeded], ["Boundaries", session.boundaries] ] as const).filter(([, xs]) => xs.length).map(([heading, xs]) => `## ${heading}\n\n${xs.map((x) => `- ${x}`).join("\n")}`).join("\n\n"); return `${buildNotesFrontmatter({ campaign: session.campaign, sessionDate: session.sessionDate })}${body}${optional ? `\n\n${optional}` : ""}\n`; }
export { atomicJson };
